ERROR - 2024-06-19 05:48:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 05:48:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 05:49:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 05:49:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 05:49:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 05:49:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 05:49:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 05:49:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(16): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 05:53:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 05:53:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:02:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:02:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:09:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:09:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:13:00 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:13:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:18:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:18:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:18:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:18:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:18:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:18:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:22:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:22:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(18): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:27:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(19): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(19): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:27:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(19): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:27:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(19): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(19): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:27:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(19): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:30:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:30:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(21): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:31:54 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->__selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->__selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:31:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(40): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(21): App\Models\CommonModel->__selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:32:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:32:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:34:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:34:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:34:58 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:34:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(21): App\Models\CommonModel->selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:36:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(23): App\Models\CommonModel->selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(23): App\Models\CommonModel->selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:36:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(38): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(23): App\Models\CommonModel->selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-06-19 06:37:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', '', '', 'sociofunda_db', 3306, '', 0)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\demo\app\Models\CommonModel.php(37): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\demo\app\Controllers\Home.php(23): App\Models\CommonModel->selectRecords('user_details')
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\demo\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\demo\system\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\demo\system\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\demo\app\Models\CommonModel.php(37): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\demo\app\Controllers\Home.php(23): App\Models\CommonModel->selectRecords('user_details')
#5 D:\xampp\htdocs\demo\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 D:\xampp\htdocs\demo\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 D:\xampp\htdocs\demo\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\demo\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\demo\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\demo\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-06-19 06:37:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user_details`', [], false)
 3 APPPATH\Models\CommonModel.php(37): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(23): App\Models\CommonModel->selectRecords('user_details')
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
